### ISSUE TITLE
Issue running mocha tests

### ISSUE THREAD

**Issue by mlippert** [stevethedev/node-kraeve#1]
This seems like an excellent idea. I just ran into an issue when trying to use kraeve in my mocha unit tests to require the sources being tested.

Seems the package located is mocha instead of my app. When kraeve wasn't finding my files I wrote out 
`"require.main.filename" =  /app/node_modules/mocha/bin/_mocha`

There are other things that could have affected this such as wtfnode as the commandline I was using was:
```
./node_modules/.bin/wtfnode ./node_modules/.bin/_mocha --reporter spec -r kraeve -r dotenv/config --recursive test/unit
```
I don't have a solution, but I figured I should at least let you know.

**Comment by stevethedev** [comment]
@mlippert 

This problem occurs because Mocha is claiming control of Kraeve before your primary repository. I have published v1.0.5 of Kraeve to NPM, which should solve this issue. This works in my local testing, but I'm going to leave this ticket open for now pending confirmation that it will also resolve the issue in your environment.

**Comment by mlippert** [comment]
Sorry, I'll test this out very soon. Thanks for figuring out a fix, I wasn't expecting any quick solution.

**Comment by stevethedev** [comment]
@mlippert No worries, take your time. If you're willing to make a ticket for the issue, I want to make sure that the problem is resolved.
